services:
  consul-change-logger:
    build:
      context: .
      dockerfile: src/ConsulChangeLogger.Proxy/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./outbox:/var/lib/consul-change-logger/outbox
    networks:
      - consul-change-logger-net

networks:
  consul-change-logger-net:
    external: true
