{{- if .Values.outbox.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.outbox.pvc.name }}
  namespace: {{ include "consul-change-logger.namespace" . }}
  labels:
    {{- include "consul-change-logger.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.outbox.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.outbox.pvc.size }}
  {{- if .Values.outbox.pvc.storageClassName }}
  storageClassName: {{ .Values.outbox.pvc.storageClassName }}
  {{- end }}
{{- end }}
