apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-change-logger-outbox
  namespace: consul
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-change-logger-dp-keys
  namespace: consul
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
