apiVersion: v1
kind: Secret
metadata:
  name: consul-change-logger-secrets
  namespace: consul
type: Opaque
stringData:
  ldap-bind-password: change-me
  elasticsearch-username: elastic
  elasticsearch-password: change-me
  elasticsearch-api-key: ""
