<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ConsulChangeLogger.Core</AssemblyName>
    <RootNamespace>ConsulChangeLogger.Core</RootNamespace>
    <Product>Consul Change Logger</Product>
    <AssemblyTitle>ConsulChangeLogger.Core</AssemblyTitle>
  </PropertyGroup>
</Project>
